#!/bin/bash

/bin/echo -e 'The mkusb console displays output from the engine behind the zenity curtain.'
cd

rdev=$(df | grep -m1 /$|cut -d ' ' -f1)
if [ "$rdev" == "/cow" ] || [ "$rdev" == "aufs" ]
then
 sudo -H mkusb
else
 which zenity > /dev/null
 if [ $? -eq 0 ]
 then
  ans=1
  cnt=0
  while [ $ans != 0 ] && [ $cnt -lt 3 ]
  do
   /bin/echo -en '\0033[37m'
   zenity --password --title='mkusb - [sudo] password' 2> /dev/null | sudo -SH mkusb
   ans=$?
   cnt=$(($cnt+1))
   /bin/echo -e "\0033[0mlogin attempt $cnt"
   sleep 2
  done
 else
  /bin/echo -en '\0033]11;#daa125\0007\0033[1mPlease install zenity or use mkusb-nox!\0033[0m'
  read -p ' (Press Enter to Exit)'
 fi
fi
