name = "datro-flywheel"
main = "src/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[limits]
subrequest_limit = 1000

[triggers]
crons = ["*/2 * * * *"]

[[kv_namespaces]]
binding = "FLYWHEEL_STATE"
id = "ed3052fb8c2249979074b6096abc64f6"

[env.production]
vars = { ENVIRONMENT = "production", CF_ACCOUNT_ID = "77672efb598df743fe4eac6762713248" }

[[env.production.kv_namespaces]]
binding = "FLYWHEEL_STATE"
id = "ed3052fb8c2249979074b6096abc64f6"
