---
# Python packages (pip)

- name: Ensure pip is upgraded
  pip:
    name: pip
    state: latest

- name: Install Python packages
  pip:
    name:
      - aiodns==3.2.0
      - aiohttp==3.11.16
      - aiosignal==1.3.2
      - alabaster==1.0.0
      - attrs==25.3.0
      - awscli==2.23.6
      - beautifulsoup4==4.13.4
      - bcrypt==4.2.0
      - boto3
      - botocore
      - certifi==2025.1.31
      - cffi
      - charset-normalizer
      - click==8.1.8
      - cryptography==43.0.0
      - flask
      - frozenlist==1.6.0
      - idna==3.10
      - jinja2==3.1.6
      - jmespath==1.0.1
      - markdown-it-py==3.0.0
      - MarkupSafe==2.1.5
      - multidict==6.4.3
      - packaging==25.0
      - paramiko==3.5.1
      - pillow==11.3.0
      - pip==25.1.1
      - platformdirs==4.3.7
      - protobuf
      - psutil==7.0.0
      - pyarrow
      - pycryptodome
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.32.3
      - rich==13.9.4
      - rpds-py==0.21.0
      - ruamel.yaml==0.18.10
      - s3transfer
      - sentry-sdk==2.18.0
      - setuptools==78.1.1
      - six
      - sphinx==9.1.0
      - sphinx-intl==2.3.2
      - sphinx-rtd-theme==3.1.0
      - sqlalchemy
      - typing-extensions==4.13.2
      - urllib3==2.3.0
      - wheel==0.46.1
      - yarl==1.19.0
    state: present
    executable: pip3

- name: Install system Python packages
  apt:
    name:
      - python3-pip
      - python3-dev
      - python3-venv
      - python3-setuptools
      - python3-wheel
      - python3-apt
      - python3-jinja2
      - python3-yaml
    state: present
