// Auto-generated by scripts/prebuild.sh from .version — do not edit manually
export async function onRequest(){return new Response(JSON.stringify({version:"1.2.0",branch:"financecheque",release:"financecheque-v1.2.0",updated:"2026-08-20T00:21:50Z"}),{status:200,headers:{"Access-Control-Allow-Origin":"*","Content-Type":"application/json"}});}
