// Auto-generated by prebuild from .version
export async function onRequest(){return new Response(JSON.stringify({version:"0.5.0.06",branch:"financecheque",release:"financecheque-v0.5.0.06"}),{status:200,headers:{"Access-Control-Allow-Origin":"*","Content-Type":"application/json"}});}
