// Auto-generated by scripts/prebuild.sh from .version — do not edit manually
export async function onRequest(){return new Response(JSON.stringify({version:"1.2.4",branch:"financecheque",release:"financecheque-v1.2.4",updated:"2026-08-20T01:03:31Z"}),{status:200,headers:{"Access-Control-Allow-Origin":"*","Content-Type":"application/json"}});}
