name = "datro-agent-api"
compatibility_date = "2024-04-01"

[vars]
DATRO_LIBRARY = "datro-assets"

[[r2_buckets]]
binding = "DATRO_LIBRARY"
bucket_name = "datro-assets"

[[routes]]
pattern = "datro.xyz/.agent/api/*"
zone_name = "datro.xyz"