#!/bin/sh
### BEGIN INIT INFO
# Provides:           switch_cpu_governor
# Required-Start:     udev mountkernfs $remote_fs
# Required-Stop:
# Default-Start:      S
# Default-Stop:
# Short-Description:  Switch to ondemand cpu governor (unless shift key is pressed)
# Description:
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
  start)
    SYS_CPUFREQ_GOVERNOR=/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
    [ -e $SYS_CPUFREQ_GOVERNOR ] && echo "ondemand" > $SYS_CPUFREQ_GOVERNOR
    echo 70 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
    printf "Switching to ondemand scaling governor"
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
