---
# Desktop Environment (Cinnamon)

- name: Set default display manager to lightdm
  systemd:
    name: lightdm
    enabled: yes

- name: Ensure cinnamon desktop is default
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: '^user-session='
    line: 'user-session=cinnamon'
    create: yes

- name: Install Cinnamon desktop extras
  apt:
    name:
      - cinnamon-desktop-environment
      - cinnamon-core
      - cinnamon-sounds
      - cinnamon-wallpapers
      - cinnamon-themes
      - cinnamon-translations
    state: present

- name: Install media codecs
  apt:
    name:
      - ubuntu-restricted-addons
      - ubuntu-restricted-extras
      - ffmpeg
      - vlc
      - libavcodec-extra
    state: present
    notify: apt clean

- name: Install printer support
  apt:
    name:
      - cups
      - cups-client
      - cups-common
      - cups-filters
      - printer-driver-brlaser
      - printer-driver-c2esp
      - printer-driver-foo2zjs
      - printer-driver-gutenprint
      - printer-driver-hpcups
      - printer-driver-m2300w
      - printer-driver-pnm2ppa
      - printer-driver-postscript-hp
      - printer-driver-ptouch
      - printer-driver-pxljr
      - printer-driver-sag-gdi
      - printer-driver-splix
      - system-config-printer
    state: present
