#!/bin/bash
# scripts/prebuild.sh — Generate version.ts from .version
# Run before Cloudflare Pages build or on version bump
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
VERSION_FILE="$REPO_ROOT/.version"
VERSION_TS="$REPO_ROOT/functions/api/version.ts"

if [[ ! -f "$VERSION_FILE" ]]; then
  echo "Error: .version not found at $VERSION_FILE" >&2
  exit 1
fi

VERSION=$(cat "$VERSION_FILE" | tr -d '[:space:]')
TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)

cat > "$VERSION_TS" << EOF
// Auto-generated by scripts/prebuild.sh from .version — do not edit manually
export async function onRequest(){return new Response(JSON.stringify({version:"${VERSION}",branch:"financecheque",release:"financecheque-v${VERSION}",updated:"${TIMESTAMP}"}),{status:200,headers:{"Access-Control-Allow-Origin":"*","Content-Type":"application/json"}});}
EOF

echo "Generated functions/api/version.ts for v${VERSION}"
