project = u'DATRO LLMWiki - Agent Memory: Long-term'
copyright = u'Finance Cheque UK'
author = u'The Team @ DATRO Consortium'
version = u'0.0.1'
release = u'0.0.1'
extensions = ['sphinx.ext.autosectionlabel', 'myst_parser']
source_suffix = {'.rst': 'restructuredtext', '.md': 'markdown'}
master_doc = 'index'
language = "en"
locale_dirs = ['locales']
gettext_auto_build = True
gettext_compact = "docs"
exclude_patterns = ['_build']
html_theme = 'sphinx_rtd_theme'
htmlhelp_basename = 'memory-longterm_longterm-honcho'
latex_elements = {'papersize': 'a4paper', 'pointsize': '10pt', 'extraclassoptions': 'openany', 'preamble': r'\usepackage{etoolbox}\patchcmd{\chapter}{\cleardoublepage}{\clearpage}{}{}'}
latex_documents = [(master_doc, 'memory-longterm_longterm-honcho.tex', u'Long-term Memory — Honcho & Mem0', u'DATRO Consortium', 'manual')]
myst_enable_extensions = ["colon_fence", "deflist"]
