#!/usr/bin/env node
// Task Router — Detects tasks vs chat, routes to agentic backends
// Chat → ollama (free local LLM)
// Task → opencode/kilo (agentic harness with MCP tools)

import http from "node:http";
import { execFile, spawn } from "node:child_process";
import { promisify } from "node:util";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";

const execFileAsync = promisify(execFile);
const PORT = parseInt(process.env.PORT || "3200");
// WS6: bind to loopback only — /route hands arbitrary text to an autonomous CLI
// with shell access, so it must never be reachable off-host. The task-router
// service generated by the installers sets Host=127.0.0.1; this explicit bind is
// the second line of defence (independent of systemd).
const HOST = process.env.TASK_ROUTER_HOST || "127.0.0.1";
// Optional shared-secret: if TASK_ROUTER_TOKEN is set, /route requires it. Both
// the router and the GUI read the same env var (from ~/.fcukproxy/.env), so a
// node with a token mints one transiently and the GUI echoes it back. When the
// token is unset we still enforce loopback-only binding.
const ROUTER_TOKEN = process.env.TASK_ROUTER_TOKEN || "";
const OMNIRUTE_URL = process.env.OMNIRUTE_URL || "http://localhost:20128";
const OPENCODE_BIN = process.env.OPENCODE_BIN || "opencode";
const KILO_BIN = process.env.KILO_BIN || "kilo";

// Task detection patterns (applied AFTER politeness prefixes are stripped)
// WS6: these are the fast-path fallback. Politeness lead-ins ("please help me
// to X", "hey can you ...") no longer force a request into task mode by
// themselves; the verb that follows decides.
const TASK_PATTERNS = [
  /^(create|write|build|make|generate|add|implement|fix|debug|refactor|deploy|test|install|configure|setup|update|modify|change|edit|rename|move|copy|delete|remove|run|execute|start|stop|restart|inspect|analyze|review|document|scaffold|init|compile|download|install)\b/i,
  /\b(install|download|configure|setup|deploy|migrate|create the file|write the|edit the|refactor the|rebuild|restart the service)\b/i,
];

// Chat patterns (bypass task routing)
const CHAT_PATTERNS = [
  /^(hi|hello|hey|yo|sup|what's up|how are you|how's it going|good morning|good evening|good night)\b/i,
  /^(what|who|where|when|why|how|which)\s+(is|are|was|were|do|does|did|can|could|would|should|will)\b/i,
  /^(what|who|where|when|why|which)\b.*\?$/i,
  /^(yes|no|ok|sure|thanks|thank you|cool|great|awesome|nice|perfect|good|bad|fine)\s*[!.?]*$/i,
  /^(I think|I feel|I like|I don't|I can't|I'm|tell me about|describe|explain)\b/i,
];

// Strip politeness/attention lead-ins so they never misroute "please help me to
// install X" as chat AND "please give me a summary" doesn't become a task just
// because it starts with "please".
function stripPoliteness(text) {
  return text
    .replace(/^(please|pls|kindly)\s+/i, "")
    .replace(/^(hey|hi|hello|yo)\s*(could|could you|cannot|can|can you|would|would you|will|will you)?\s+/i, "$1")
    .replace(/^((could|could you|can|can you|would|would you|will|will you|do|does|did)\s+(you|u|ya)\s+)/i, "")
    .replace(/^(help|help me|please help me|help me to|please help me to)\s+/i, "")
    .replace(/^i want (you to|to)\s+/i, "")
    .trim();
}

function isTask(text) {
  const trimmed = text.trim();

  // Check chat patterns first (short circuit)
  for (const pattern of CHAT_PATTERNS) {
    if (pattern.test(trimmed)) return false;
  }

  // Very short messages are likely chat
  if (trimmed.length < 10) return false;

  // Strip politeness prefixes ("help me", "please", "can you") so the intent
  // that follows decides — "help me install X" is a task, "help" alone is chat.
  const core = stripPoliteness(trimmed);

  // Bare acknowledgement / "help" without a task verb is chat.
  if (/^(help|help me|please)\s*$/i.test(trimmed)) return false;

  // Check task patterns against the de-politened text
  for (const pattern of TASK_PATTERNS) {
    if (pattern.test(core)) return true;
  }

  // Strong action verbs buried in a longer sentence → task
  if (/\b(install|download|fix|debug|create|build|write|configure|deploy|refactor|remove|delete)\s+(the|a|an|this|that|my|our|your)?\s+\w+/i.test(core)) {
    return true;
  }

  // Default: if it's long and structured, treat as task
  return trimmed.length > 50 && !/\?$/.test(trimmed);
}

// Path to the tool-use wrapper script (ensures agent backends have exec capabilities)
const TOOL_WRAPPER = path.join(
  path.dirname(process.argv[1]), // this script's dir
  "..", "public", "fcukproxy", "tool-use-wrapper.sh"
);

async function routeToOpencode(task) {
  return new Promise((resolve, reject) => {
    const timeout = setTimeout(() => {
      child.kill();
      reject(new Error("opencode timeout (5 min)"));
    }, 300_000);

    // Use the tool-use wrapper to ensure proper tool configuration
    const useWrapper = fs.existsSync(TOOL_WRAPPER);
    const bin = useWrapper ? TOOL_WRAPPER : OPENCODE_BIN;
    const args = useWrapper ? ["opencode", task] : ["run", task];

    const child = spawn(bin, args, {
      cwd: process.env.HOME || "/home/unclehowell",
      env: {
        ...process.env,
        NONINTERACTIVE: "1",
        // Ensure the agent knows it has tool access
        AGENT_TOOL_ACCESS: "full",
      },
      stdio: ["pipe", "pipe", "pipe"],
    });

    let stdout = "";
    let stderr = "";

    child.stdout.on("data", (data) => { stdout += data.toString(); });
    child.stderr.on("data", (data) => { stderr += data.toString(); });

    child.on("close", (code) => {
      clearTimeout(timeout);
      if (code === 0) {
        resolve(stdout || "Task completed (no output)");
      } else {
        // Detect "I cannot" / "I don't have capability" refusals and provide guidance
        const output = (stderr || stdout || "").toLowerCase();
        if (output.includes("cannot perform") || output.includes("don't have the capability") || output.includes("unable to execute")) {
          resolve(`Agent refused to execute this task. Ensure the agent backend has tool-use configured.\n\nOriginal output:\n${stderr || stdout}`);
        } else {
          resolve(stderr || stdout || `Task failed with exit code ${code}`);
        }
      }
    });

    child.on("error", (err) => {
      clearTimeout(timeout);
      reject(err);
    });
  });
}

async function routeToKilo(task) {
  return new Promise((resolve, reject) => {
    const timeout = setTimeout(() => {
      child.kill();
      reject(new Error("kilo timeout (5 min)"));
    }, 300_000);

    // Use the tool-use wrapper to ensure proper tool configuration
    const useWrapper = fs.existsSync(TOOL_WRAPPER);
    const bin = useWrapper ? TOOL_WRAPPER : KILO_BIN;
    const args = useWrapper ? ["kilo", task] : ["--chat", task];

    const child = spawn(bin, args, {
      cwd: process.env.HOME || "/home/unclehowell",
      env: {
        ...process.env,
        NONINTERACTIVE: "1",
        // Ensure the agent knows it has tool access
        AGENT_TOOL_ACCESS: "full",
      },
      stdio: ["pipe", "pipe", "pipe"],
    });

    let stdout = "";
    let stderr = "";

    child.stdout.on("data", (data) => { stdout += data.toString(); });
    child.stderr.on("data", (data) => { stderr += data.toString(); });

    child.on("close", (code) => {
      clearTimeout(timeout);
      if (code === 0) {
        resolve(stdout || "Task completed (no output)");
      } else {
        // Detect "I cannot" / "I don't have capability" refusals and provide guidance
        const output = (stderr || stdout || "").toLowerCase();
        if (output.includes("cannot perform") || output.includes("don't have the capability") || output.includes("unable to execute")) {
          resolve(`Agent refused to execute this task. Ensure the agent backend has tool-use configured.\n\nOriginal output:\n${stderr || stdout}`);
        } else {
          resolve(stderr || stdout || `Task failed with exit code ${code}`);
        }
      }
    });

    child.on("error", (err) => {
      clearTimeout(timeout);
      reject(err);
    });
  });
}

async function routeTask(task) {
  // Try opencode first (primary agentic backend)
  try {
    const result = await routeToOpencode(task);
    return { backend: "opencode", result };
  } catch (err) {
    console.log(`[task-router] opencode failed: ${err.message}, trying kilo...`);
  }

  // Fallback to kilo
  try {
    const result = await routeToKilo(task);
    return { backend: "kilo", result };
  } catch (err) {
    console.log(`[task-router] kilo failed: ${err.message}`);
    return { backend: "none", result: "No agentic backend available. Install opencode or kilo." };
  }
}

// HTTP server for task routing API
const server = http.createServer(async (req, res) => {
  // CORS
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");

  if (req.method === "OPTIONS") {
    res.writeHead(204);
    res.end();
    return;
  }

  if (req.method === "GET" && req.url === "/health") {
    res.writeHead(200, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ 
      status: "ok",
      backends: {
        opencode: await checkBinary(OPENCODE_BIN),
        kilo: await checkBinary(KILO_BIN),
      }
    }));
    return;
  }

  if (req.method === "POST" && req.url === "/route") {
    // WS6: require the shared secret for /route when one is configured. The GUI
    // reads the same TASK_ROUTER_TOKEN (from ~/.fcukproxy/.env) and echoes it.
    if (ROUTER_TOKEN && `Bearer ${ROUTER_TOKEN}` !== (req.headers.authorization || "")) {
      res.writeHead(401, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ error: "unauthorized" }));
      return;
    }
    let body = "";
    for await (const chunk of req) body += chunk;

    try {
      const { text, messages } = JSON.parse(body);
      const input = text || (messages?.length ? messages[messages.length - 1].content : "");

      if (!input) {
        res.writeHead(400, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ error: "text or messages required" }));
        return;
      }

      const isTaskRequest = isTask(input);

      if (!isTaskRequest) {
        // Chat — route to ollama via OmniRoute
        res.writeHead(200, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ type: "chat", backend: "ollama", input }));
        return;
      }

      // Task — route to agentic backend
      console.log(`[task-router] Task detected: "${input.slice(0, 80)}..."`);
      const { backend, result } = await routeTask(input);

      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ type: "task", backend, result }));
    } catch (err) {
      res.writeHead(500, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ error: err.message }));
    }
    return;
  }

  res.writeHead(404, { "Content-Type": "application/json" });
  res.end(JSON.stringify({ error: "Not found" }));
});

async function checkBinary(name) {
  try {
    await execFileAsync("which", [name]);
    return true;
  } catch {
    return false;
  }
}

server.listen(PORT, HOST, () => {
  console.log(`[task-router] Running on http://${HOST}:${PORT}`);
  console.log(`[task-router] opencode: ${OPENCODE_BIN}`);
  console.log(`[task-router] kilo: ${KILO_BIN}`);
  console.log(`[task-router] auth: ${ROUTER_TOKEN ? "required (shared secret)" : "loopback-only (no token configured)"}`);
});
