#!/usr/bin/env node
// Task Router — Detects tasks vs chat, routes to agentic backends
// Chat → ollama (free local LLM)
// Task → opencode/kilo (agentic harness with MCP tools)

import http from "node:http";
import { execFile, spawn } from "node:child_process";
import { promisify } from "node:util";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";

const execFileAsync = promisify(execFile);
const PORT = parseInt(process.env.PORT || "3200");
// WS6: bind to loopback only — /route hands arbitrary text to an autonomous CLI
// with shell access, so it must never be reachable off-host. The task-router
// service generated by the installers sets Host=127.0.0.1; this explicit bind is
// the second line of defence (independent of systemd).
const HOST = process.env.TASK_ROUTER_HOST || "127.0.0.1";
// Optional shared-secret: if TASK_ROUTER_TOKEN is set, /route requires it. Both
// the router and the GUI read the same env var (from ~/.fcukproxy/.env), so a
// node with a token mints one transiently and the GUI echoes it back. When the
// token is unset we still enforce loopback-only binding.
const ROUTER_TOKEN = process.env.TASK_ROUTER_TOKEN || "";
const OMNIRUTE_URL = process.env.OMNIRUTE_URL || "http://localhost:20128";
const OPENCODE_BIN = process.env.OPENCODE_BIN || "opencode";
const KILO_BIN = process.env.KILO_BIN || "kilo";
const KIRO_BIN = process.env.KIRO_BIN || "kiro-cli";

// Task detection patterns (applied AFTER politeness prefixes are stripped)
// WS6: these are the fast-path fallback. Politeness lead-ins ("please help me
// to X", "hey can you ...") no longer force a request into task mode by
// themselves; the verb that follows decides.
const TASK_PATTERNS = [
  /^(create|write|build|make|generate|add|implement|fix|debug|refactor|deploy|test|install|configure|setup|update|modify|change|edit|rename|move|copy|delete|remove|run|execute|start|stop|restart|inspect|analyze|review|document|scaffold|init|compile|download|install)\b/i,
  /\b(install|download|configure|setup|deploy|migrate|create the file|write the|edit the|refactor the|rebuild|restart the service)\b/i,
];

// Chat patterns (bypass task routing)
const CHAT_PATTERNS = [
  /^(hi|hello|hey|yo|sup|what's up|how are you|how's it going|good morning|good evening|good night)\b/i,
  /^(what|who|where|when|why|how|which)\s+(is|are|was|were|do|does|did|can|could|would|should|will)\b/i,
  /^(what|who|where|when|why|which)\b.*\?$/i,
  /^(yes|no|ok|sure|thanks|thank you|cool|great|awesome|nice|perfect|good|bad|fine)\s*[!.?]*$/i,
  /^(I think|I feel|I like|I don't|I can't|I'm|tell me about|describe|explain)\b/i,
];

// Strip politeness/attention lead-ins so they never misroute "please help me to
// install X" as chat AND "please give me a summary" doesn't become a task just
// because it starts with "please".
function stripPoliteness(text) {
  return text
    .replace(/^(please|pls|kindly)\s+/i, "")
    .replace(/^(hey|hi|hello|yo)\s*(could|could you|cannot|can|can you|would|would you|will|will you)?\s+/i, "$1")
    .replace(/^((could|could you|can|can you|would|would you|will|will you|do|does|did)\s+(you|u|ya)\s+)/i, "")
    .replace(/^(help|help me|please help me|help me to|please help me to)\s+/i, "")
    .replace(/^i want (you to|to)\s+/i, "")
    .trim();
}

function isTask(text) {
  const trimmed = text.trim();

  // Check chat patterns first (short circuit)
  for (const pattern of CHAT_PATTERNS) {
    if (pattern.test(trimmed)) return false;
  }

  // Very short messages are likely chat
  if (trimmed.length < 10) return false;

  // Strip politeness prefixes ("help me", "please", "can you") so the intent
  // that follows decides — "help me install X" is a task, "help" alone is chat.
  const core = stripPoliteness(trimmed);

  // Bare acknowledgement / "help" without a task verb is chat.
  if (/^(help|help me|please)\s*$/i.test(trimmed)) return false;

  // Check task patterns against the de-politened text
  for (const pattern of TASK_PATTERNS) {
    if (pattern.test(core)) return true;
  }

  // Strong action verbs buried in a longer sentence → task
  if (/\b(install|download|fix|debug|create|build|write|configure|deploy|refactor|remove|delete)\s+(the|a|an|this|that|my|our|your)?\s+\w+/i.test(core)) {
    return true;
  }

  // Default: if it's long and structured, treat as task
  return trimmed.length > 50 && !/\?$/.test(trimmed);
}

// Path to the tool-use wrapper script (ensures agent backends have exec capabilities)
// Git nodes run this file from $INSTALL_DIR/agentos/, so the script-relative
// candidate resolves to $INSTALL_DIR/public/fcukproxy/tool-use-wrapper.sh.
// Tarball nodes deploy the router to ~/.fcukproxy/omniroute/ while the wrapper
// goes to ~/.fcukproxy/, so we check the deployed home-dir candidate too.
const TOOL_WRAPPER_CANDIDATES = [
  path.join(path.dirname(process.argv[1]), "..", "public", "fcukproxy", "tool-use-wrapper.sh"),
  path.join(os.homedir(), ".fcukproxy", "tool-use-wrapper.sh"),
];
const TOOL_WRAPPER = TOOL_WRAPPER_CANDIDATES.find((p) => fs.existsSync(p)) || "";

// ── WS-08: file-backed task resume ledger ──────────────────
// One JSON per in-flight task so a task-router crash or restart doesn't
// silently strand a run the GUI believes is executing. Storage contract
// (AGENTS.md): files are removed when the run reaches a terminal state
// (done/failed) or after 7 days.
const LEDGER_DIR = path.join(os.homedir(), ".fcukproxy", "ledger", "tasks");
const LEDGER_MAX_AGE_MS = 7 * 24 * 60 * 60 * 1000;

function ledgerTaskId() {
  return "task-" + Date.now().toString(36) + Math.random().toString(36).slice(2, 6);
}

function ledgerWrite(entry) {
  try {
    fs.mkdirSync(LEDGER_DIR, { recursive: true });
    const tmp = path.join(LEDGER_DIR, `${entry.id}.tmp`);
    fs.writeFileSync(tmp, JSON.stringify(entry, null, 2), "utf-8");
    fs.renameSync(tmp, path.join(LEDGER_DIR, `${entry.id}.json`));
  } catch (err) {
    console.log(`[task-router] ledger write failed: ${err.message}`);
  }
}

function ledgerClear(id) {
  try {
    fs.unlinkSync(path.join(LEDGER_DIR, `${id}.json`));
  } catch {
    /* already gone */
  }
}

function ledgerPrune() {
  try {
    fs.mkdirSync(LEDGER_DIR, { recursive: true });
    const now = Date.now();
    for (const name of fs.readdirSync(LEDGER_DIR)) {
      if (!name.endsWith(".json")) continue;
      const p = path.join(LEDGER_DIR, name);
      try {
        if (now - fs.statSync(p).mtimeMs > LEDGER_MAX_AGE_MS) fs.unlinkSync(p);
      } catch {
        /* skip */
      }
    }
  } catch {
    /* dir may be unavailable */
  }
}

function ledgerList() {
  try {
    fs.mkdirSync(LEDGER_DIR, { recursive: true });
    return fs.readdirSync(LEDGER_DIR)
      .filter((name) => name.endsWith(".json"))
      .map((name) => {
        try {
          return JSON.parse(fs.readFileSync(path.join(LEDGER_DIR, name), "utf-8"));
        } catch {
          return null;
        }
      })
      .filter(Boolean)
      .sort((a, b) => (b.startedAt || 0) - (a.startedAt || 0));
  } catch {
    return [];
  }
}

// WS-10 (v1.11.35): tool-use enforcement. Agents are spawned with
// AGENT_TOOL_ACCESS=full; this directive is appended on a REFUSAL so the
// backend stops claiming it lacks capability and actually uses its tools.
const TOOL_USE_DIRECTIVE = `

---

IMPORTANT: You have FULL tool access on this machine (shell/terminal, file
read-write, git, web fetch/search, python). Do NOT refuse this task by saying
you cannot perform it or lack the capability to execute it — you CAN and DO
have those tools. Use them: inspect the environment (read the relevant files),
then actually do the work. If a tool fails, try a different approach instead
of giving up. Finish by reporting in one paragraph what you changed and the
result.`;

// Refusal phrase detection (task-router's existing heuristic, kept exact so the
// behaviour shift is minimal): with WS-10 we respond by RETRYING once with the
// tool-use directive instead of just relaying the refusal to the caller.
function isRefusal(output) {
  const t = (output || "").toLowerCase();
  return (
    /cannot perform/.test(t) ||
    /don['’]?t have the capability/.test(t) ||
    /do not have the capability/.test(t) ||
    /unable to execute/.test(t) ||
    /i (am )?not able to/.test(t) ||
    /no capability/.test(t) ||
    /refus(e|ing|ed)/.test(t)
  );
}

function runBackend({ bin, args, label, timeoutMs, env }) {
  return new Promise((resolve, reject) => {
    const child = spawn(bin, args, {
      cwd: process.env.HOME || "/home/unclehowell",
      env,
      stdio: ["pipe", "pipe", "pipe"],
    });
    let stdout = "";
    let stderr = "";
    const timer = setTimeout(() => {
      child.kill();
      reject(new Error(`${label} timeout (${Math.round(timeoutMs / 60000)} min)`));
    }, timeoutMs);
    child.stdout.on("data", (data) => { stdout += data.toString(); });
    child.stderr.on("data", (data) => { stderr += data.toString(); });
    child.on("close", (code) => {
      clearTimeout(timer);
      resolve({ code, stdout, stderr });
    });
    child.on("error", (err) => {
      clearTimeout(timer);
      reject(err);
    });
  });
}

function backendOutput(out, label) {
  if (out.code === 0) return out.stdout || "Task completed (no output)";
  if (isRefusal(out.stderr || out.stdout)) {
    return {
      refusal: true,
      output: out.stderr || out.stdout || `Task exited with code ${out.code}`,
    };
  }
  return out.stderr || out.stdout || `Task failed with exit code ${out.code}`;
}

async function routeToOpencode(task) {
  // Use the tool-use wrapper to ensure proper tool configuration
  const useWrapper = fs.existsSync(TOOL_WRAPPER);
  const bin = useWrapper ? TOOL_WRAPPER : OPENCODE_BIN;
  const mkArgs = (t) => (useWrapper ? ["opencode", t] : ["run", t]);
  const run = () =>
    runBackend({
      bin,
      args: mkArgs(task),
      label: "opencode",
      timeoutMs: 300_000,
      env: { ...process.env, NONINTERACTIVE: "1", AGENT_TOOL_ACCESS: "full" },
    });
  const out = await run();
  const first = backendOutput(out, "opencode");
  if (typeof first !== "string" && first.refusal) {
    console.log(`[task-router] opencode refused — retrying once with tool-use directive`);
    const retry = await runBackend({
      bin,
      args: mkArgs(task + TOOL_USE_DIRECTIVE),
      label: "opencode (tool-use retry)",
      timeoutMs: 300_000,
      env: { ...process.env, NONINTERACTIVE: "1", AGENT_TOOL_ACCESS: "full" },
    });
    const second = backendOutput(retry, "opencode");
    if (typeof second === "string") return second;
    return `Agent refused to execute this task after a tool-use retry. Unless the backend is misconfigured, it should have used its tools.\n\nOriginal output:\n${first.output}`;
  }
  return first;
}

async function routeToKilo(task) {
  // Use the tool-use wrapper to ensure proper tool configuration
  const useWrapper = fs.existsSync(TOOL_WRAPPER);
  const bin = useWrapper ? TOOL_WRAPPER : KILO_BIN;
  const mkArgs = (t) => (useWrapper ? ["kilo", t] : ["run", t]);
  const run = () =>
    runBackend({
      bin,
      args: mkArgs(task),
      label: "kilo",
      timeoutMs: 300_000,
      env: { ...process.env, NONINTERACTIVE: "1", AGENT_TOOL_ACCESS: "full" },
    });
  const out = await run();
  const first = backendOutput(out, "kilo");
  if (typeof first !== "string" && first.refusal) {
    console.log(`[task-router] kilo refused — retrying once with tool-use directive`);
    const retry = await runBackend({
      bin,
      args: mkArgs(task + TOOL_USE_DIRECTIVE),
      label: "kilo (tool-use retry)",
      timeoutMs: 300_000,
      env: { ...process.env, NONINTERACTIVE: "1", AGENT_TOOL_ACCESS: "full" },
    });
    const second = backendOutput(retry, "kilo");
    if (typeof second === "string") return second;
    return `Agent refused to execute this task after a tool-use retry. Unless the backend is misconfigured, it should have used its tools.\n\nOriginal output:\n${first.output}`;
  }
  return first;
}

async function routeToKiro(task) {
  // kiro-cli (npm: @aws/kiro-cli) takes a chat subcommand; run it
  // headless with trust-all-tools so agentic prompts execute end-to-end.
  const run = () =>
    runBackend({
      bin: KIRO_BIN,
      args: ["chat", "--no-interactive", "--trust-all-tools", task],
      label: "kiro",
      timeoutMs: 300_000,
      env: { ...process.env, NONINTERACTIVE: "1", AGENT_TOOL_ACCESS: "full" },
    });
  const out = await run();
  return backendOutput(out, "kiro");
}

async function routeTask(task) {
  // WS-08: ledger the run BEFORE dispatching so a crash mid-task leaves a
  // recoverable record (GET /ledger). Cleared on every terminal outcome.
  const taskId = ledgerTaskId();
  const startedAt = Date.now();
  const base = { id: taskId, task, startedAt };
  ledgerWrite({ ...base, backend: "opencode", status: "running" });

  // Try opencode first (primary agentic backend)
  try {
    const result = await routeToOpencode(task);
    ledgerClear(taskId);
    return { backend: "opencode", result };
  } catch (err) {
    ledgerWrite({ ...base, backend: "kilo", status: "running", note: `opencode failed: ${err.message}` });
    console.log(`[task-router] opencode failed: ${err.message}, trying kilo...`);
  }

  // Fallback to kilo
  try {
    const result = await routeToKilo(task);
    ledgerClear(taskId);
    return { backend: "kilo", result };
  } catch (err) {
    ledgerWrite({ ...base, backend: "kiro", status: "running", note: `kilo failed: ${err.message}` });
    console.log(`[task-router] kilo failed: ${err.message}, trying kiro...`);
  }

  // Final fallback to kiro (AWS kiro-cli)
  try {
    const result = await routeToKiro(task);
    ledgerClear(taskId);
    return { backend: "kiro", result };
  } catch (err) {
    ledgerWrite({ ...base, backend: "none", status: "failed", note: err.message });
    console.log(`[task-router] kiro failed: ${err.message}`);
    return { backend: "none", result: "No agentic backend available. Install opencode, kilo, or kiro." };
  }
}

// HTTP server for task routing API
const server = http.createServer(async (req, res) => {
  // CORS
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");

  if (req.method === "OPTIONS") {
    res.writeHead(204);
    res.end();
    return;
  }

  if (req.method === "GET" && req.url === "/health") {
    res.writeHead(200, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ 
      status: "ok",
      backends: {
        opencode: await checkBinary(OPENCODE_BIN),
        kilo: await checkBinary(KILO_BIN),
        kiro: await checkBinary(KIRO_BIN),
      },
      inFlight: ledgerList().filter((e) => e.status === "running").length,
    }));
    return;
  }

  if (req.method === "GET" && req.url === "/ledger") {
    // WS-08: in-flight (non-terminal) task records, newest first — for crash
    // resume and for the GUI's tasks view.
    res.writeHead(200, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ ledger: ledgerList().filter((e) => e.status !== "done" && e.status !== "failed") }));
    return;
  }

  if (req.method === "POST" && req.url === "/route") {
    // WS6: require the shared secret for /route when one is configured. The GUI
    // reads the same TASK_ROUTER_TOKEN (from ~/.fcukproxy/.env) and echoes it.
    if (ROUTER_TOKEN && `Bearer ${ROUTER_TOKEN}` !== (req.headers.authorization || "")) {
      res.writeHead(401, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ error: "unauthorized" }));
      return;
    }
    let body = "";
    for await (const chunk of req) body += chunk;

    try {
      const { text, messages } = JSON.parse(body);
      const input = text || (messages?.length ? messages[messages.length - 1].content : "");

      if (!input) {
        res.writeHead(400, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ error: "text or messages required" }));
        return;
      }

      const isTaskRequest = isTask(input);

      if (!isTaskRequest) {
        // Chat — route to ollama via OmniRoute
        res.writeHead(200, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ type: "chat", backend: "ollama", input }));
        return;
      }

      // Task — route to agentic backend
      console.log(`[task-router] Task detected: "${input.slice(0, 80)}..."`);
      const { backend, result } = await routeTask(input);

      res.writeHead(200, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ type: "task", backend, result }));
    } catch (err) {
      res.writeHead(500, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ error: err.message }));
    }
    return;
  }

  res.writeHead(404, { "Content-Type": "application/json" });
  res.end(JSON.stringify({ error: "Not found" }));
});

async function checkBinary(name) {
  try {
    await execFileAsync("which", [name]);
    return true;
  } catch {
    return false;
  }
}

server.listen(PORT, HOST, () => {
  ledgerPrune();
  console.log(`[task-router] Running on http://${HOST}:${PORT}`);
  console.log(`[task-router] opencode: ${OPENCODE_BIN}`);
  console.log(`[task-router] kilo: ${KILO_BIN}`);
  console.log(`[task-router] kiro: ${KIRO_BIN}`);
  console.log(`[task-router] auth: ${ROUTER_TOKEN ? "required (shared secret)" : "loopback-only (no token configured)"}`);
});
